[mysqld]
# Cac thiet lap co ban
port=3306
character-set-server=utf8mb4
default-storage-engine=INNODB
max_allowed_packet=64M
innodb_buffer_pool_size=256M
skip-name-resolve

# Khong ghi cung basedir/datadir o day de tang tinh di dong
# Chung ta se truyen qua dong lenh trong start.bat

[client]
port=3306
default-character-set=utf8mb4
